name: flutter_ui
description: A Flutter UI package,include action sheet,badge,button,check list,datetime picker,
  field,index list etc...
version: 0.1.0
author: xiaomo <hupengbest@gmail.com>
homepage: https://github.com/flutter-jp/flutter_ui

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.15+1
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

